### ISSUE TITLE
Houdini Engine for Unreal compilation error.

### ISSUE THREAD

**Issue by slick3d** [sideeffects/HoudiniEngineForUnreal#210]
Hello. I've got this error while compiling the Houdini Engine on Unreal 5.1 on Rocky Linux 9. I believe that's a code error. Here are the screenshots with the error. Thanks for any help.
![Screenshot_20221116_231745](https://user-images.githubusercontent.com/60118168/202339411-a5463bdd-ec92-494b-a595-320fc3447a61.jpg)
![Screenshot_20221116_231809](https://user-images.githubusercontent.com/60118168/202339426-09961116-a494-4373-8e87-a09b10b3ad02.jpg)

**Comment by Utopialjp** [comment]
I've got similar problem. Thanks for any help.

-HoudiniEngineForUnreal branch: Houdini19.5-Unreal5.00
-UnrealEngine: 5.0.3
-Platform: Ubuntu20.04

**Comment by dpernuit** [comment]
Hi,
Have you tried using the latest sources?
Those linux only error should be fixed.

**Comment by Utopialjp** [comment]
> Hi, Have you tried using the latest sources? Those linux only error should be fixed.

Hi, thanks for your replay. I pulled the latest branch Houdini19.5-Unreal5.00, but the problem still exist. The commit is 
![Screenshot from 2022-12-06 14-02-46](https://user-images.githubusercontent.com/23400855/205833076-46cafb75-ba20-4f68-84f6-1a70923e5ef3.png)

The compile error:
`[37/86] Compile MapInterface.gen.cpp
[38/86] Compile Module.HoudiniEngine.1_of_7.cpp
In file included from /home/xxx/xxx/xxx/xxx/xxx/Unreal/SolarEngineUE5/Plugins/HoudiniEngine/Intermediate/Build/Linux/B4D820EA/UnrealEditor/Development/HoudiniEngine/Module.HoudiniEngine.1_of_7.cpp:6:
[1m/home/xxx/xxx/xxx/xxx/xxx/Unreal/SolarEngineUE5/Plugins/HoudiniEngine/Source/HoudiniEngine/Private/HoudiniDataTableTranslator.cpp:1098:129: [0m[0;1;31merror: [0m[1mcannot initialize a parameter of type 'HAPI_Int64 *' (aka 'long *') with an rvalue of type 'int64 *' (aka 'long long *')[0m
                                Result = FHoudiniApi::GetAttributeInt64Data(FHoudiniEngine::Get().GetSession(), GeoId, PartId, AttribName, &AttribInfo, -1, static_cast<int64*>(Data), 0, AttribInfo.count);
[0;1;32m                                                                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~
[0m1 error generated.

[65/86] Compile Module.WebUI.cpp
[66/86] Compile Module.HoudiniEngine.2_of_7.cpp
In file included from /home/xxx/xxx/xxx/xxx/xxx/Unreal/SolarEngineUE5/Plugins/HoudiniEngine/Intermediate/Build/Linux/B4D820EA/UnrealEditor/Development/HoudiniEngine/Module.HoudiniEngine.2_of_7.cpp:8:
[1m/home/xxx/xxx/xxx/xxx/xxx/Unreal/SolarEngineUE5/Plugins/HoudiniEngine/Source/HoudiniEngine/Private/HoudiniEngineUtils.cpp:3760:24: [0m[0;1;31merror: [0m[1mcannot initialize a parameter of type 'const HAPI_Int64 *' (aka 'const long *') with an rvalue of type 'const int64 *' (aka 'const long long *')[0m
                                        &InAttributeInfo, InInt64Data + ChunkStart * InAttributeInfo.tupleSize,
[0;1;32m                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m[1m/home/xxx/xxx/xxx/xxx/xxx/Unreal/SolarEngineUE5/Plugins/HoudiniEngine/Source/HoudiniEngine/Private/HoudiniEngineUtils.cpp:3791:23: [0m[0;1;31merror: [0m[1mcannot initialize a parameter of type 'const HAPI_Int64 *' (aka 'const long *') with an lvalue of type 'const int64 *' (aka 'const long long *')[0m
                                &InAttributeInfo, InInt64Data,
[0;1;32m                                                  ^~~~~~~~~~~
[0m2 errors generated.
`
The project detail:
- UnrealEngine: 5.0.3
- Houdini: hfs19.5.451
- Platform: Ubuntu20.04
